name: PHP 7.3

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare code
        run: |
          touch docker-compose.env
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> docker-compose.env
          echo "CODECOMMIT_HOST=${{ secrets.CODECOMMIT_HOST }}" >> docker-compose.env
          echo "CODECOMMIT_USER=${{ secrets.CODECOMMIT_USER }}" >> docker-compose.env
          echo "CODECOMMIT_PASSWORD=${{ secrets.CODECOMMIT_PASSWORD }}" >> docker-compose.env

      - name: Run tests
        run: |
          docker-compose -f docker-compose-73.yml up --build -d

          echo $(docker run -t --network php-dev jwilder/dockerize \
            -wait http://php-dev_nginx/ \
            -timeout 60s)

          docker ps -a

          docker logs php-dev_app

          CONTENT=$(curl -s "http://127.0.0.1/");
          echo "CHAMADA HTTP: ${CONTENT}";

          if [ "${CONTENT}" != "Like Sistemas|73" ]; then
            echo "Chamada HTTP retornou errado: ${CONTENT}"
            exit 1;
          fi

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            PHP_VERSION=73
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            likesistemas/php-dev:latest
            likesistemas/php-dev:73
            likesistemas/php-dev:7.3
            ghcr.io/likesistemas/php-dev:latest
            ghcr.io/likesistemas/php-dev:73
            ghcr.io/likesistemas/php-dev:7.3
